border_width = 2
margin = [4, 4]
default_border_color = "#0E1512"
floating_border_color = "#C36B97"
focused_border_color = "#9bc3cb"


col1 = "#1C5360"
col2 = "#536065"
col3 = "#AC3A54"
col4 = "#1B6790"
col5 = "#476491"
col6 = "#C36B97"
col7 = "#9bc3cb"
col8 = "#6c888e"
col9 = "#1C5360"
col10 = "#536065"
col11 = "#AC3A54"
col12 = "#1B6790"
col13 = "#476491"
col14 = "#C36B97"
col15 = "#9bc3cb"



background = "#0E1512"
foreground = "#9bc3cb"
