border_width = 2
margin = [4, 4]
default_border_color = "#040508"
floating_border_color = "#AC5CAE"
focused_border_color = "#a4c3cf"


col1 = "#2C4E61"
col2 = "#545E66"
col3 = "#9E7366"
col4 = "#36599E"
col5 = "#5A6B95"
col6 = "#AC5CAE"
col7 = "#a4c3cf"
col8 = "#728890"
col9 = "#2C4E61"
col10 = "#545E66"
col11 = "#9E7366"
col12 = "#36599E"
col13 = "#5A6B95"
col14 = "#AC5CAE"
col15 = "#a4c3cf"



background = "#040508"
foreground = "#a4c3cf"
